Jest: Setup jest to run with Playwright 
hariclerry/mediawiki pull request #17
Opened 2020-12-13 19:04 UTC by hariclerry

### Tickets
Closes #13  

### What does this PR do?
- This PR setup jest to run with Playwright

### What are the changes made?
- Installed jest
- Installed jest-playwright-preset
- Added configuration for jest and playwright

### Screen shots
None

2020-12-14 09:37 UTC, und3fined-v01d requested changes

2020-12-14 09:37 UTC, und3fined-v01d commented on tests/playwright/jest-playwright.config.js
> +		headless: false
This should not be hardcoded. We should essentially set an environment variable which if not exists runs in headless by default

2020-12-14 09:37 UTC, und3fined-v01d commented on tests/playwright/jest.e2e.config.js
> +	testMatch: [ '**/tests/playwright/specs/**/*.js' ],
nice job done fixing this

2020-12-14 09:37 UTC, und3fined-v01d commented on tests/playwright/specs/wikipediaHomePage.js
> +	it( 'test if page loads successfully', async () => {
The describe and the test together should form a language...for example

the `describe` block says "Wikipedia Home Page"

so the `it` block should read "should load successfully"

2020-12-14 09:37 UTC, und3fined-v01d commented on tests/playwright/specs/wikipediaHomePage.js
> +	it( 'should check if page sub title is correct', async () => {
Same as above

2020-12-14 09:53 UTC, und3fined-v01d requested changes

2020-12-14 09:53 UTC, und3fined-v01d commented on package.json
> +    "jest-test": "jest -c ./tests/playwright/jest.e2e.config.js"
Add scripts:

`playwright:open`: Run in non-headless mode
`playwright:close`: Run in headless mode

2020-12-14 09:53 UTC, und3fined-v01d commented on tests/playwright/specs/wikipediaHomePage.js
> +	it( 'should check if page sub title is correct', async () => {
Make a single test which checks only the subtitle as if the subtitle loads it implies that the page has loaded correctly

2020-12-14 13:39 UTC, hariclerry commented
@und3fined-v01d, I have implemented the requested changes. Please review and let me know if everything is fine. Thanks

2020-12-15 10:10 UTC, und3fined-v01d requested changes

2020-12-15 10:10 UTC, sovoid commented on tests/playwright/jest.e2e.config.js
> +	preset: 'jest-playwright-preset',
check where this should be added

2020-12-15 10:10 UTC, sovoid commented on tests/playwright/jest-playwright.config.js
> +		headless: false
This is not being read from the configuration file oddly. Please verify  if the config is correct

2020-12-15 10:10 UTC, und3fined-v01d commented on tests/playwright/README.md
> +- Run `npm ci`
Update README and add optional environment variables that can be set along with their defaults

2020-12-15 10:10 UTC, und3fined-v01d commented on tests/playwright/README.md
> +- Run `npm run jest-test`
update this command to new one and add a note that it runs headless by default

2020-12-15 11:46 UTC, vidhi-mody approved these changes

2020-12-15 11:49 UTC, und3fined-v01d approved these changes

2020-12-15 11:49 UTC, merged