Travis CI: Clean up nodejs config from travis file
hariclerry/mediawiki pull request #23
Opened 2020-12-18 03:18 UTC by hariclerry

### Tickets
Closes #21 

### What does this PR do?
This PR removes nodejs config from .travis.yml file, reverts the file to the previous state, and adds Github actions status badge to the README file

### What are the changes made?
- Remove Node configuration from travis.yml file
- Added previous configurations to the file
- Added Github actions status badge to the Readme file

### Screen shots
None

2020-12-18 10:09 UTC, und3fined-v01d requested changes

2020-12-18 10:09 UTC, und3fined-v01d commented on .github/workflows/node.js.yml
> +
Remove the extra whitespace here

2020-12-18 10:15 UTC, und3fined-v01d requested changes

2020-12-18 10:15 UTC, und3fined-v01d commented on .github/workflows/node.js.yml
> +    - run: npm run playwright:silent
Add names to the jobs that are verbose. `npm run <script-name>` isnt really explicit about what the script does

2020-12-18 14:37 UTC, hariclerry commented
@und3fined-v01d , I have made the necessary changes.

2020-12-21 10:14 UTC, und3fined-v01d requested changes

2020-12-21 10:14 UTC, und3fined-v01d commented on .github/workflows/node.js.yml
> +# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
Add this file to a separate pull request

2020-12-21 11:28 UTC, closed without merging