Travis Cl:  Clean up travis configurations for playwright tests
hariclerry/mediawiki pull request #26
Opened 2020-12-21 12:05 UTC by hariclerry

### Tickets
Closes #22

### What does this PR do?
This PR removes nodejs config from .travis.yml file, reverts the file to the previous state, and adds remove travis ci status badge to the README file

### What are the changes made?
- Remove Node configuration from travis.yml file
- Added previous configurations to the file
- Remove travis CI status badge from the Readme file

### Screen shots
None

2020-12-23 11:11 UTC, vidhi-mody requested changes
The .github/workflows/node.js.yml should be in a separate PR. This PR should only contain changes related to the Travis CI cleanup.

2020-12-24 06:47 UTC, und3fined-v01d requested changes

2020-12-24 06:47 UTC, und3fined-v01d commented on .github/workflows/node.js.yml
> +            - name: "Run eslint"
Please add this file in a separate PR

2020-12-24 07:09 UTC, hariclerry commented
Hello @vidhi-mody, those changes are coming in because I rebased with master.

2020-12-24 07:47 UTC, und3fined-v01d commented
@hariclerry these changes should not be visible here even if they are from master. You must be doing something wrong while rebasing

2020-12-27 21:08 UTC, closed without merging