Set up Node in TravisCI
hariclerry/mediawiki pull request #3
Opened 2020-12-03 22:01 UTC by hariclerry

### What does this PR do?
This PR creates a .travis.yml file and adds configurations for Nodejs.

### What are the changes made?
- Created .travis.yml file
- Added Node configuration to the .travis.yml file
- Ran npm ci

### Screen shots
None

2020-12-03 22:12 UTC, hariclerry commented
Hey all, I have a few questions regarding this PR;
1. Should I add the repository to my Travis CI account to ensure the setup is working or are we doing this later?
2. Should I add other commands that may be necessary now or later, for example, the `service` command? please advise accordingly.

2020-12-04 11:59 UTC, und3fined-v01d commented
@hariclerry the service commands should follow based on the issue. This issue explicitly says set up nodejs so that's what should be done in the PR. Feel free to add the repo to your Travis I account since we would need to run the code there

2020-12-04 16:51 UTC, hariclerry commented
Noted @und3fined-v01d, I have added the repo to my Travis CI account.

2020-12-05 06:38 UTC, und3fined-v01d commented
@hariclerry please install the TravisCI app on this repo as well so that we can see the logs as well

2020-12-05 06:39 UTC, und3fined-v01d requested changes

2020-12-05 06:39 UTC, und3fined-v01d commented on .travis.yml
> +
Please remove the extra newline

2020-12-06 20:19 UTC, hariclerry commented on .travis.yml
> +
This has been fixed.

2020-12-07 19:21 UTC, merged